{
	"app":{
		"host_name":"<ip>",
		"node_name":"HKVPS",
		"port_number":1235,
		"root_dir":"/root/rpi/web",
		"wsport_number":1236
	},
	"data":{
		"root_dir":"/root/data/"
	},
        "web":{
               "baseurl":"http://<ip>:1235/",
               "host":"<ip>",
               "wsport":"1236"
        }
}
